
api:
  key: 4P0xIsuOQIRoGEQBvs0ZJJyEuxpYi38G
  url: ${API_URL:https://api.apilayer.com/exchangerates_data/convert}

server:
  port: 6007

spring:
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${USERNAME:postgres}
    password: ${PASSWORD:mysecretpassword}
    url: ${URL:jdbc:postgresql://localhost:5432/software}
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: currency-converter

keycloak:
  auth-server-url: http://localhost:9090
  autodetect-bearer-only: true
  credentials:
    secret: dH8SLOVQIus1f703zsbsRLBbGLY9crlk
  realm: software
  resource: backend
  ssl-required: external
  use-resource-role-mappings: false
  security-constraints:
    - auth-roles:
        - ADMIN
      security-collections:
        - name: SERVICIOS DEL ADMINISTRADOR
          methods:
            - GET
          patterns:
            - /api/currency/*
